version: '3.6'

services:
  db:
    image: mysql:8.0.32
    container_name: demo-park-mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: demo_park

    ports:
      - '3306:3306'